# Generated by Django 6.0.4 on 2026-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('j_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=50)),
                ('material', models.CharField(choices=[('Leather', 'Leather'), ('Synthetic', 'Synthetic'), ('Suede', 'Suede')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jacket_images/')),
            ],
        ),
    ]
